//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40218.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace FormInDesignMode
{
	using System;
	using System.IO;
	using System.Resources;


	// This class was auto-generated by the Strongly Typed Resource Builder
	// class via a tool like ResGen or Visual Studio.NET.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	sealed class Resources
	{

		private static System.Resources.ResourceManager _resMgr;

		private Resources()
		{
		}

		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
		public static System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if ((_resMgr == null))
				{
					System.Resources.ResourceManager temp = new System.Resources.ResourceManager(typeof(Resources));
					System.Threading.Thread.MemoryBarrier();
					_resMgr = temp;
				}
				return _resMgr;
			}
		}
	}
}
