//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40527.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.BoosterSamples.CustomizeToolStripTest.Properties {
    using System;
    using System.IO;
    using System.Resources;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the Strongly Typed Resource Builder
    // class via a tool like ResGen or Visual Studio.NET.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    class Resources {
        
        private static System.Resources.ResourceManager _resMgr;
        
        private static System.Globalization.CultureInfo _resCulture;
        
        /*FamANDAssem*/ internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if ((_resMgr == null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.Samples.BoosterSamples.CustomizeToolStripTest.Properties.Resources", typeof(Resources).Assembly);
                    _resMgr = temp;
                }
                return _resMgr;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return _resCulture;
            }
            set {
                _resCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap addclient {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("addclient", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap enterbill {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("enterbill", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap findappt {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("findappt", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap findbill {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("findbill", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap findclient {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("findclient", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap helpcontents {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("helpcontents", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap removeappt {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("removeappt", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap removebill {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("removebill", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap removeclient {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("removeclient", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap schednewappt {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("schednewappt", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap showallappts {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("showallappts", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap showallbills {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("showallbills", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap showallclients {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("showallclients", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap showappt {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("showappt", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap showbill {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("showbill", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap showindclient {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("showindclient", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap toolsmngprov {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("toolsmngprov", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap toolsoptions {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("toolsoptions", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap updateappt {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("updateappt", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap updatebill {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("updatebill", _resCulture)));
            }
        }
    }
}
